[lift]
name = "domestica"
description = "Sequence analysis and codon optimization"
# Target platforms for the final binaries
platforms = ["linux-x86_64", "windows-x86_64", "macos-x86_64", "macos-aarch64"]

# Define the standalone Python interpreter to bundle
[[lift.interpreters]]
id = "cpython"
provider = "PythonBuildStandalone"
version = "3.10.13"
release = "20231002"

# Map the PEX file
[[lift.files]]
name = "domesticator.pex"

# Tell the Scie how to execute when the user runs the binary
[[lift.commands]]
exe = "#{cpython:python}"
args = ["{domesticator.pex}"]
env = { PYTHONUNBUFFERED = "1" }